[general]
import = [
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/kanagawa.toml",
]


[env]
TERM = "xterm-256color"


[font]
size= 14
offset.x = 1
offset.y = 2
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font", style = "Italic" }


[window]
decorations = "transparent"  # buttonless / full / none
opacity = 0.93
startup_mode = "Windowed"
padding = { x = 4, y = 24 }
dimensions  = { columns = 165, lines = 50 }
position = { x = 350, y = 150}


[scrolling]
history = 5000
multiplier = 3


[selection]
save_to_clipboard = true
