[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
dim_foreground = "#928374"
bright_foreground = "#fbf1c7"

[colors.cursor]
text = "#282828"
cursor = "#fe8019"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#d3869b"

[colors.search.matches]
foreground = "#282828"
background = "#fabd2f"

[colors.search.focused_match]
foreground = "#282828"
background = "#b8bb26"

[colors.footer_bar]
foreground = "#282828"
background = "#fabd2f"

[colors.hints.start]
foreground = "#282828"
background = "#d79921"

[colors.hints.end]
foreground = "#282828"
background = "#fabd2f"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#282828"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#928374"

[[colors.indexed_colors]]
index = 16
color = "#d65d0e"

[[colors.indexed_colors]]
index = 17
color = "#fbf1c7"

