[keyboard]
bindings = [
  { key = "P",          mods = "Control|Shift",     action = "Paste" },
  { key = "Y",          mods = "Control|Shift",     action = "Copy" },
  { key = "Key0",       mods = "Control",           action = "ResetFontSize" },
  { key = "Equals",     mods = "Control",           action = "IncreaseFontSize" },
  { key = "N",          mods = "Control",           action = "SpawnNewInstance" },
  # option + arrow
  { key = "Left",       mods = "Alt",               chars = "\u001bb" },
  { key = "Right",      mods = "Alt",               chars = "\u001bf" },
]

